<?php

namespace jc\SlideshowBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends EntityRepository {

    public function getMaxRankForSlideshow($slideshow) {

        try {

            $query = $this->_em->createQuery('SELECT MAX(p.rank) FROM jcSlideshowBundle:Picture p JOIN p.slideshow s WHERE s.id = :slideshowId');
            $query->setParameter('slideshowId', $slideshow->getId());

            return $query->getSingleScalarResult();
        }
        catch (Exception $ex) {
            return '1';
        }
    }
}
