<?php

namespace jc\EnglishQuizzBundle\Repository\Common;

/**
 * EnglishWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface CommonEnglishItemRepository {

    /**
     * Common method to get english items from database...
     * @param array $idList List of identifiers to exclude from search.
     * @param integer $lesson Optionnal lesson to filter result.
     * @return array English items found.
     */
    public function getItemExcludingIds($idList, $lesson = 0);

    /**
     * Common method to count english items in database...
     * @param integer $lesson Optionnal lesson to filter result.
     * @return integer Numver of items found.
     */
    public function countItem($lesson = 0);

    /**
     * Common method to search english items in database...
     * @param string $property Property used to filter items.
     * @param string $value Value used to filter items.
     * @return array list of items.
     */
    public function searchItem($property, $value);
}
