<?php

namespace jc\SkinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SkinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkinRepository extends EntityRepository {

    public function disallowDefaultSkin() {

        try {

            $query = $this->_em->createQuery('UPDATE jcSkinBundle:Skin s SET s.activ=0');
            return $query->execute();
        }
        catch (Exception $ex) {
            return false;
        }
    }
}
