<?php

namespace jc\DoodleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DoodleReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoodleReplyRepository extends EntityRepository
{
    /**
     * Allows to get doodle reply relative to specified user and for specified doodle id.
     * @param jc\UserBundle\Entity\User $user User we want to find relative reply.
     * @param integer $doodleId Identifier of doodle we want to get reply.
     * @return Doodle reply matching specified user and doodle identifier, NULL if user has not yet reply to specified doodle.
     */
    public function getReplyForUserAndDoodleId($user, $doodleId) {

        $queryBuilder = $this->createQueryBuilder('dr');
        $queryBuilder = $queryBuilder->join('dr.doodle', 'd')
                ->join('dr.user', 'u')
                ->where('d.id = :doodleId')
                ->setParameter('doodleId', $doodleId)
                ->andWhere('u = :user')
                ->setParameter('user', $user);

        $query = $queryBuilder->getQuery();

        $result = $query->getResult();
        if (count($result) == 1)
            return $result[0];

        return null;
    }

    /**
     * Allows to get all reply for specified user.
     * @param jc\UserBundle\Entity\User $user User we want to find relative reply.
     * @return Doodle reply list matching specified user.
     */
    public function getReplyForUser($user) {

        $queryBuilder = $this->createQueryBuilder('dr');
        $queryBuilder = $queryBuilder->join('dr.doodle', 'd')
                ->join('dr.user', 'u')
                ->where('u = :user')
                ->setParameter('user', $user);

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }
}
