jc_news_fo_index:
    path:  /news/{id}
    defaults: { _controller: "jcNewsBundle:NewsFO:display", id: 0 }

jc_news_bo_list:
    path:  /admin/news/list
    defaults: { _controller: "jcNewsBundle:NewsBO:listNews" }

jc_news_bo_edit:
    path:  /admin/news/edit/{id}
    defaults: { _controller: "jcNewsBundle:NewsBO:editNews", id: 0 }

jc_news_bo_delete:
    path:  /admin/news/delete/{id}
    defaults: { _controller: "jcNewsBundle:NewsBO:deleteNews" }
    requirements:
        id: \d+
