
jc_contact:
    resource: "@jcContactBundle/Controller/"
    type:     annotation

jc_doodle:
    resource: "@jcDoodleBundle/Resources/config/routing.yml"
    prefix:   /

jc_ftp_slideshow:
    resource: "@jcFTPSlideshowBundle/Resources/config/routing.yml"
    prefix:   /

jc_home:
    resource: "@jcHomeBundle/Controller/"
    type:     annotation

jc_menu:
    resource: "@jcMenuBundle/Controller/"
    type:     annotation

jc_news:
    resource: "@jcNewsBundle/Controller/"
    type:     annotation

jc_skin:
    resource: "@jcSkinBundle/Controller/"
    type:     annotation

jc_skyrim:
    resource: "@jcSkyrimBundle/Resources/config/routing.yml"
    prefix:   /

jc_slideshow:
    resource: "@jcSlideshowBundle/Controller/"
    type:     annotation

jc_static_text:
    resource: "@jcStaticTextBundle/Controller/"
    type:     annotation

jc_sudoku:
    resource: "@jcSudokuBundle/Resources/config/routing.yml"
    prefix:   /

jc_test:
    resource: "@jcTestBundle/Resources/config/routing.yml"
    prefix:   /

jc_training_session:
    resource: "@jcTrainingSessionBundle/Resources/config/routing.yml"
    prefix:   /

jc_user:
    resource: "@jcUserBundle/Controller/"
    type:     annotation

jc_user_file:
    resource: "@jcUserFileBundle/Controller/"
    type:     annotation
    