security:

    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        jc\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        user_service:
            entity: { class: jc\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        resources:
            pattern:  ^/resources
            security: false
        main:
            pattern:  ^/
            anonymous: true
            provider: user_service
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /
                invalidate_session: false

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
