<?php

namespace jc\FTPSlideshowBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SlideshowRepository
 * WARNING : Request used in this repository requires jcDatabaseBundle to call specific SQL functions for dates.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideshowRepository extends EntityRepository
{
}
