parameters:
#    jc_contact.example.class: jc\ContactBundle\Example

services:
#    jc_contact.example:
#        class: %jc_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
