jc_skin_bo_list:
    path:  /admin/skin/list
    defaults: { _controller: "jcSkinBundle:SkinBO:listSkin" }

jc_skin_bo_default:
    path:  /admin/skin/default
    defaults: { _controller: "jcSkinBundle:SkinBO:defaultSkin", id: 0 }

jc_skin_bo_edit:
    path:  /admin/skin/edit/{id}
    defaults: { _controller: "jcSkinBundle:SkinBO:editSkin", id: 0 }

jc_skin_bo_delete:
    path:  /admin/skin/delete/{id}
    defaults: { _controller: "jcSkinBundle:SkinBO:deleteSkin" }
    requirements:
        id: \d+

jc_skin_fo:
    path:  /layout/skin
    defaults: { _controller: "jcSkinBundle:SkinFO:display" }
