jc\SkinBundle\Entity\Skin:
    properties:
        name:
            - NotBlank: 
                 message: "Ce champ est obligatoire"
            - Length:
                max: 255
                maxMessage: "Ce champ est limité à 255 caractères"
        cssFile:
            - NotBlank: 
                 message: "Ce champ est obligatoire"
