
jc_static_text_fo:
    path:     /staticText/{code}
    defaults: { _controller: "jcStaticTextBundle:StaticTextFO:display" }

jc_static_text_bo_list:
    path:     /admin/staticText/list
    defaults: { _controller: "jcStaticTextBundle:StaticTextBO:list" }

jc_static_text_bo_edit:
    path:  /admin/staticText/edit/{id}
    defaults: { _controller: "jcStaticTextBundle:StaticTextBO:edit", id: 0 }

jc_static_text_bo_delete:
    path:  /admin/staticText/delete/{id}
    defaults: { _controller: "jcStaticTextBundle:StaticTextBO:delete" }
    requirements:
        id: \d+
