parameters:
#    jc_static_text.example.class: jc\StaticTextBundle\Example

services:
#    jc_static_text.example:
#        class: %jc_static_text.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
