jc\StaticTextBundle\Entity\StaticText:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: code
            message: "Ce code est déjà utilisé"
    properties:
        title:
            - NotBlank: 
                 message: "Ce champ est obligatoire"
            - Length:
                max: 255
                maxMessage: "Ce champ est limité à 255 caractères"
        content:
            - NotBlank: 
                 message: "Ce champ est obligatoire"
        code:
            - NotBlank: 
                 message: "Ce champ est obligatoire"
