
jc_user_file_bo_index:
    path: /admin/userfile/index
    defaults: { _controller: "jcUserFileBundle:UserFile:index" }

jc_user_file_bo_upload:
    path: /admin/userfile/upload
    defaults: { _controller: "jcUserFileBundle:UserFile:upload" }

jc_user_file_bo_folder:
    path: /admin/userfile/folder
    defaults: { _controller: "jcUserFileBundle:UserFile:folder" }

jc_user_file_bo_delete:
    path: /admin/userfile/ajax/delete
    defaults: { _controller: "jcUserFileBundle:UserFile:delete" }

jc_user_file_bo_explore:
    path: /admin/userfile/ajax/explore
    defaults: { _controller: "jcUserFileBundle:UserFile:explore" }
