
jc_test_index:
    path: /test
    defaults: { _controller: "jcTestBundle:Test:test" }

jc_test_form_simple:
    path:     /testFormSimple
    defaults: { _controller: "jcTestBundle:TestForm:simpleTest" }

jc_test_form_complex:
    path:     /testFormComplex
    defaults: { _controller: "jcTestBundle:TestForm:complexTest" }

jc_test_form_complex_list:
    path:     /testFormComplexList
    defaults: { _controller: "jcTestBundle:TestForm:complexListTest" }
