<?php

namespace jc\TrainingSessionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository {

    /**
     * Allows to count number of location available for training session.
     * @return Number of locations.
     */
    public function countTrainingSessionLocation() {

        try {

            $query = $this->_em->createQuery('SELECT COUNT(l) FROM jcTrainingSessionBundle:Location l');
            return $query->getSingleScalarResult();
        }
        catch (Exception $ex) {
            return 0;
        }
    }
}
