<?php

namespace jc\TrainingSessionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingSessionRepository extends EntityRepository {

    /**
     * Allows to know if training session exist with specified contact.
     * @param jc\TrainingSessionBundle\Entity\Contact $contact Contact we want to know if it is used by any training session.
     * @return TRUE if contact is used by any training session, FALSE either.
     */
    public function isTrainingSessionWithContact($contact) {

        try {

            $query = $this->_em->createQuery('SELECT COUNT(ts) FROM jcTrainingSessionBundle:TrainingSession ts WHERE ts.contact = :contact');
            $query->setParameter('contact', $contact);

            return ($query->getSingleScalarResult() > 0);
        }
        catch (Exception $ex) {
            return true;
        }
    }

    /**
     * Allows to know if training session exist with specified location.
     * @param jc\TrainingSessionBundle\Entity\Location $location Location we want to know if it is used by any training session.
     * @return TRUE if location is used by any training session, FALSE either.
     */
    public function isTrainingSessionWithLocation($location) {

        try {

            $query = $this->_em->createQuery('SELECT COUNT(ts) FROM jcTrainingSessionBundle:TrainingSession ts WHERE ts.location = :location');
            $query->setParameter('location', $location);

            return ($query->getSingleScalarResult() > 0);
        }
        catch (Exception $ex) {
            return true;
        }
    }
}
