<?php

namespace jc\TrainingSessionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingSessionRepository extends EntityRepository
{
}
