<?php

namespace jc\ParisOiseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function getOrderedDocumentForConstruction($construction) {

        try {

            $query = $this->_em->createQuery('SELECT d FROM jcParisOiseBundle:Document d JOIN d.type dt WHERE d.construction = :construction ORDER BY dt.rank ASC');
            $query->setParameter('construction', $construction);

            return $query->getResult();
        }
        catch (Exception $ex) {
            return array();
        }
    }
}
