<?php

namespace jc\StaticTextBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StaticTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticTextRepository extends EntityRepository {

    public function countStaticText() {

        try {

            $query = $this->_em->createQuery('SELECT COUNT(st) FROM jcStaticTextBundle:StaticText st');
            return $query->getSingleScalarResult();
        }
        catch (Exception $ex) {
            return 0;
        }
    }

    public function getMaxRank() {

        try {

            $query = $this->_em->createQuery('SELECT MAX(st.rank) FROM jcStaticTextBundle:StaticText st');
            return $query->getSingleScalarResult();
        }
        catch (Exception $ex) {
            return '1';
        }
    }
}
