<?php

namespace jc\StaticTextBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StaticTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticTextRepository extends EntityRepository
{
}
