parameters:
    jc_tool.pagination: 5

services:
    jc_tool.pagination:
        class: 'jc\ToolBundle\Service\PaginationService'
        arguments: [ '@doctrine.orm.entity_manager', '%jc_tool.pagination%' ]
    jc_tool.twig.truncate:
        class: jc\ToolBundle\Twig\TruncateExtension
        tags:
            - { name: twig.extension }
