<?php

namespace jc\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function getMaxRank()
    {
        try
        {
            $query = $this->_em->createQuery('SELECT MAX(m.rank) FROM jcMenuBundle:Menu m');
            return $query->getSingleScalarResult();
        }
        catch (Exception $ex) {
            return '1';
        }
    }
}
