
jc_user_bo_list:
    path:     /admin/user/list
    defaults: { _controller: "jcUserBundle:User:list" }
jc_user_bo_edit:
    path:     /admin/user/edit/{id}
    defaults: { _controller: "jcUserBundle:User:edit", id: 0 }
jc_user_bo_delete:
    path:     /admin/user/delete/{id}
    defaults: { _controller: "jcUserBundle:User:delete" }

jc_user_password:
    path: /password
    defaults: { _controller: "jcUserBundle:Account:password" }
jc_user_account:
    path: /user/account
    defaults: { _controller: "jcUserBundle:Account:account" }

login:
    path: /login
    defaults: { _controller: "jcUserBundle:Login:login" }
login_check:
    path: /login_check
logout:
    path: /logout
