parameters:
    jc_user.prefix_mail: JC
    jc_user.from_mail: jc@aequum.fr
    jc_user.from_name: JC

services:
    jc_user.account_mail:
        class: 'jc\UserBundle\Service\AccountMailService'
        arguments: [ '%jc_user.prefix_mail%', '%jc_user.from_mail%', '%jc_user.from_name%' ]
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setMailer, ['@mailer']]
            - [setTemplating, ['@templating']]
