jc\QuizzBundle\Entity\Quizz:
    properties:
        name:
            - NotBlank: 
                 message: "Ce champ est obligatoire"
            - Length:
                max: 255
                maxMessage: "Ce champ est limité à 255 caractères"

jc\QuizzBundle\Entity\QuizzResponse:
    properties:
        title:
            - NotBlank: 
                 message: "Ce champ est obligatoire"
            - Length:
                max: 255
                maxMessage: "Ce champ est limité à 255 caractères"
