<?php

namespace jc\EnglishQuizzBundle\Repository;

use jc\EnglishQuizzBundle\Repository\Common\CommonEnglishItemRepository;
use Doctrine\ORM\EntityRepository;

/**
 * EnglishIrregularVerbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnglishIrregularVerbRepository extends EntityRepository implements CommonEnglishItemRepository {

    public function getItemExcludingIds($idList, $lesson = 0) {

        try {

            $condition = '';
            if ($idList)
                $condition .= ' AND i.id NOT IN (' . implode(',', $idList) . ')';

            if (strlen($condition))
                $condition = 'WHERE ' . substr($condition, 4);

            $query = $this->_em->createQuery('SELECT i FROM jcEnglishQuizzBundle:EnglishIrregularVerb i ' . $condition);
            return $query->getResult();
        }
        catch(\Exception $ex) {
            return array();
        }
    }

    public function countItem($lesson = 0) {

        try {

            $query = $this->_em->createQuery('SELECT count(i) FROM jcEnglishQuizzBundle:EnglishIrregularVerb i');
            return $query->getSingleScalarResult();
        }
        catch(\Exception $ex) {
            return 0;
        }
    }

    public function searchItem($property, $value) {

        try {

            $query = $this->_em->createQuery('SELECT i FROM jcEnglishQuizzBundle:EnglishIrregularVerb i WHERE i.' . $property . ' LIKE \'%' . $value . '%\'');
            return $query->getResult();
        }
        catch(\Exception $ex) {
            return array();
        }
    }
}
